version: "3.8"
services:
  test3.2:
    image: "public.ecr.aws/lambda/ruby:3.2-${ARCH}"
    entrypoint: ./bin/_test
    volumes:
      - $PWD:/var/task
    depends_on:
      mysql:
         condition: service_healthy
    links:
      - mysql
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10
